### ISSUE TITLE
No puedo ejecutar desde una pagina web

### ISSUE THREAD

**Issue by irmajulia** [irmaDevelop/sendit#3]
# Brindanos una descripcion corta. No mas de 20 caracteres.
Quiero ejecutar la funcion sin tener que bajarla a mi computadora
# Clasifica el problema
[ ] error
[ x] incidente

# Indica la rama o ramas en donde se presentó el problema.
Master
# Describe paso a paso, como replicar el problema.
No existe la funcion

**Comment by irmaDevelop** [comment]
En este momento no tenemos personal para desarrollar la mejora

**Comment by irmajulia** [comment]
Volvere a fastidiar luego
